## Phase 5 FDA + Clinical Trial Ablations (Local Runbook)

Use this notebook top-to-bottom on your local machine.

1. Local environment setup and project path check
2. Dependency install (if needed)
3. Run Ablation 4 (`basic_fda`)
4. Run Ablation 5 (`rich_fda`)
5. Run Ablation 5+CT (`rich_fda_ct`) for confound-aware context
6. Inspect artifacts and comparison outputs

This runbook is local-first and does not require Colab zip extraction.

In [1]:
# Local setup (run once per fresh kernel)
from pathlib import Path
import os
import sys

# If notebook is opened from project root, this should already be correct.
PROJECT_DIR = Path.cwd()
if not (PROJECT_DIR / 'phase5_fda_ppo.py').exists():
    # TODO: set this manually if your kernel cwd is elsewhere.
    PROJECT_DIR = Path('/Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project ')

os.chdir(PROJECT_DIR)

print('cwd:', os.getcwd())
print('python:', sys.executable)
print('project_dir:', PROJECT_DIR)
print('phase5 script exists:', Path('phase5_fda_ppo.py').exists())
print('train csv exists:', Path('processed/train_dataset.csv').exists())

cwd: /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project
python: /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project /.venv/bin/python
project_dir: /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project
phase5 script exists: True
train csv exists: True

In [2]:
# Dependencies (safe to re-run)
# In local venv this can be skipped if already installed.
%pip install -q numpy pandas gymnasium stable-baselines3

Note: you may need to restart the kernel to use updated packages.

In [3]:
# Phase 5 Ablation 4: basic FDA (lighter run)
import subprocess
import sys

cmd = [
    sys.executable,
    'phase5_fda_ppo.py',
    '--project-root', str(PROJECT_DIR),
    '--ablation', 'basic_fda',
    '--timesteps', '60000',
    '--search-timesteps', '15000',
    '--seeds', '7,42',
    '--val-split-date', '2021-01-01',
    '--sent-clip', '3.0',
    '--seed', '42',
    '--window-size', '20',
    '--device', 'auto',
]
print('Running:', ' '.join(cmd))
subprocess.run(cmd, check=True)

Running: /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project /.venv/bin/python phase5_fda_ppo.py --project-root /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project  --ablation basic_fda --timesteps 60000 --search-timesteps 15000 --seeds 7,42 --val-split-date 2021-01-01 --sent-clip 3.0 --seed 42 --window-size 20 --device auto
Using PPO params from: /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project /results/phase4_tuning/best_params_price_sentiment.json
Ablation: basic_fda
Num features (price/sent/fda): 17 5 5
Sequence window: 20
Robust seeds: [7, 42]
Timesteps (final): 60000 | search: 15000
Device: auto
[candidate=base_tuned] score=-4.0535 sharpe=-3.3681 ret=0.0643 mdd=-0.1591 sell/hold/buy=0.125/0.562/0.312
[candidate=lower_lr_small_net] score=-4.1284 sharpe=-3.3666 ret=0.0192 mdd=-0.2027 sell/hold/buy=0.000/0.688/0.312
[candidate=low_lr_stable_steps] score=-3.8543 sharpe=-3.1333 ret=0.0362 mdd=-0.1260 sell/hold/buy=0.000/0.750/0.250
[candidate=no_exploration_late] score=-2.7723 sharpe=-2.2585 ret=0.1755 mdd=-0.1356 sell/hold/buy=0.062/0.441/0.496
Saved model: /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project /results/phase5_basic_fda/ppo_phase5_fda.zip
Selected candidate: no_exploration_late
Selected seed: 7
Saved: /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project /results/phase5_basic_fda/phase3_phase4_phase5_comparison.csv

Saved artifacts:
 - /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project /results/phase5_basic_fda/phase5_fda_metrics.csv
 - /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project /results/phase5_basic_fda/phase5_fda_equity_curve.csv
 - /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project /results/phase5_basic_fda/phase5_fda_actions.csv
 - /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project /results/phase5_basic_fda/phase5_action_distribution.csv
 - /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project /results/phase5_basic_fda/phase5_robust_search_trials.csv
 - /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project /results/phase5_basic_fda/phase5_run_metadata.json
 - /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project /results/phase5_basic_fda/phase5_fda_interpretability.csv
 - /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project /results/phase5_basic_fda/ppo_phase5_fda.zip

Top metrics:
           strategy  cumulative_return_pct  ann_sharpe  ann_sortino  max_drawdown_pct  win_rate  alpha_vs_xph_ann_pct
PPO_Phase5_BasicFDA              25.431256    0.613396     1.061182        -17.527683  0.497006             16.125121
      BuyHold_Equal               9.625921    0.377820     0.613220        -17.925456  0.508982              7.737318
EqualWeight_Monthly               8.460957    0.339634     0.554942        -18.982354  0.500998              7.237284
                XPH              -8.074730   -0.090723    -0.145941        -22.619079  0.491018              0.000000
       Momentum_20D              -8.401114   -0.171261    -0.254539        -24.221550  0.465070             -0.998788

CompletedProcess(args=['/Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project /.venv/bin/python', 'phase5_fda_ppo.py', '--project-root', '/Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project ', '--ablation', 'basic_fda', '--timesteps', '60000', '--search-timesteps', '15000', '--seeds', '7,42', '--val-split-date', '2021-01-01', '--sent-clip', '3.0', '--seed', '42', '--window-size', '20', '--device', 'auto'], returncode=0)

In [4]:
# Phase 5 Ablation 5: rich FDA (lighter run)
import subprocess
import sys

cmd = [
    sys.executable,
    'phase5_fda_ppo.py',
    '--project-root', str(PROJECT_DIR),
    '--ablation', 'rich_fda',
    '--timesteps', '60000',
    '--search-timesteps', '15000',
    '--seeds', '7,42',
    '--val-split-date', '2021-01-01',
    '--sent-clip', '3.0',
    '--seed', '42',
    '--window-size', '20',
    '--device', 'auto',
]
print('Running:', ' '.join(cmd))
subprocess.run(cmd, check=True)

Running: /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project /.venv/bin/python phase5_fda_ppo.py --project-root /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project  --ablation rich_fda --timesteps 60000 --search-timesteps 15000 --seeds 7,42 --val-split-date 2021-01-01 --sent-clip 3.0 --seed 42 --window-size 20 --device auto
Using PPO params from: /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project /results/phase4_tuning/best_params_price_sentiment.json
Ablation: rich_fda
Num features (price/sent/fda): 17 5 15
Sequence window: 20
Robust seeds: [7, 42]
Timesteps (final): 60000 | search: 15000
Device: auto
[candidate=base_tuned] score=-3.1086 sharpe=-2.5448 ret=0.1443 mdd=-0.1517 sell/hold/buy=0.125/0.438/0.438
[candidate=lower_lr_small_net] score=-3.2161 sharpe=-2.8387 ret=0.2659 mdd=-0.1312 sell/hold/buy=0.000/0.688/0.312
[candidate=low_lr_stable_steps] score=-4.1805 sharpe=-3.5408 ret=0.0940 mdd=-0.1536 sell/hold/buy=0.000/0.750/0.250
[candidate=no_exploration_late] score=-3.3968 sharpe=-2.8254 ret=0.1481 mdd=-0.2178 sell/hold/buy=0.125/0.582/0.293
Saved model: /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project /results/phase5_rich_fda/ppo_phase5_fda.zip
Selected candidate: base_tuned
Selected seed: 7
Saved: /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project /results/phase5_rich_fda/phase3_phase4_phase5_comparison.csv

Saved artifacts:
 - /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project /results/phase5_rich_fda/phase5_fda_metrics.csv
 - /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project /results/phase5_rich_fda/phase5_fda_equity_curve.csv
 - /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project /results/phase5_rich_fda/phase5_fda_actions.csv
 - /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project /results/phase5_rich_fda/phase5_action_distribution.csv
 - /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project /results/phase5_rich_fda/phase5_robust_search_trials.csv
 - /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project /results/phase5_rich_fda/phase5_run_metadata.json
 - /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project /results/phase5_rich_fda/phase5_fda_interpretability.csv
 - /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project /results/phase5_rich_fda/ppo_phase5_fda.zip

Top metrics:
           strategy  cumulative_return_pct  ann_sharpe  ann_sortino  max_drawdown_pct  win_rate  alpha_vs_xph_ann_pct
      BuyHold_Equal               9.625921    0.377820     0.613220        -17.925456  0.508982              7.737318
EqualWeight_Monthly               8.460957    0.339634     0.554942        -18.982354  0.500998              7.237284
 PPO_Phase5_RichFDA               5.016599    0.222449     0.390616        -25.551392  0.502994              6.488123
                XPH              -8.074730   -0.090723    -0.145941        -22.619079  0.491018              0.000000
       Momentum_20D              -8.401114   -0.171261    -0.254539        -24.221550  0.465070             -0.998788

CompletedProcess(args=['/Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project /.venv/bin/python', 'phase5_fda_ppo.py', '--project-root', '/Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project ', '--ablation', 'rich_fda', '--timesteps', '60000', '--search-timesteps', '15000', '--seeds', '7,42', '--val-split-date', '2021-01-01', '--sent-clip', '3.0', '--seed', '42', '--window-size', '20', '--device', 'auto'], returncode=0)

In [5]:
# Phase 5 Ablation 5+CT: rich FDA + clinical-trial confound context (lighter run)
import subprocess
import sys

cmd = [
    sys.executable,
    'phase5_fda_ppo.py',
    '--project-root', str(PROJECT_DIR),
    '--ablation', 'rich_fda_ct',
    '--timesteps', '60000',
    '--search-timesteps', '15000',
    '--seeds', '7,42',
    '--val-split-date', '2021-01-01',
    '--sent-clip', '3.0',
    '--seed', '42',
    '--window-size', '20',
    '--device', 'auto',
]
print('Running:', ' '.join(cmd))
subprocess.run(cmd, check=True)

Running: /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project /.venv/bin/python phase5_fda_ppo.py --project-root /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project  --ablation rich_fda_ct --timesteps 60000 --search-timesteps 15000 --seeds 7,42 --val-split-date 2021-01-01 --sent-clip 3.0 --seed 42 --window-size 20 --device auto
Using PPO params from: /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project /results/phase4_tuning/best_params_price_sentiment.json
Ablation: rich_fda_ct
Num features (price/sent/fda): 17 5 21
Sequence window: 20
Robust seeds: [7, 42]
Timesteps (final): 60000 | search: 15000
Device: auto
[candidate=base_tuned] score=-4.2400 sharpe=-3.5231 ret=0.0433 mdd=-0.1594 sell/hold/buy=0.062/0.688/0.250
[candidate=lower_lr_small_net] score=-4.2015 sharpe=-3.5766 ret=0.1048 mdd=-0.1607 sell/hold/buy=0.000/0.780/0.220
[candidate=low_lr_stable_steps] score=-3.5094 sharpe=-2.8245 ret=0.0614 mdd=-0.1353 sell/hold/buy=0.000/0.688/0.312
[candidate=no_exploration_late] score=-5.3235 sharpe=-4.5175 ret=-0.0084 mdd=-0.2171 sell/hold/buy=0.062/0.812/0.125
Saved model: /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project /results/phase5_rich_fda_ct/ppo_phase5_fda.zip
Selected candidate: low_lr_stable_steps
Selected seed: 42
Saved: /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project /results/phase5_rich_fda_ct/phase3_phase4_phase5_comparison.csv

Saved artifacts:
 - /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project /results/phase5_rich_fda_ct/phase5_fda_metrics.csv
 - /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project /results/phase5_rich_fda_ct/phase5_fda_equity_curve.csv
 - /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project /results/phase5_rich_fda_ct/phase5_fda_actions.csv
 - /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project /results/phase5_rich_fda_ct/phase5_action_distribution.csv
 - /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project /results/phase5_rich_fda_ct/phase5_robust_search_trials.csv
 - /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project /results/phase5_rich_fda_ct/phase5_run_metadata.json
 - /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project /results/phase5_rich_fda_ct/phase5_fda_interpretability.csv
 - /Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project /results/phase5_rich_fda_ct/ppo_phase5_fda.zip

Top metrics:
             strategy  cumulative_return_pct  ann_sharpe  ann_sortino  max_drawdown_pct  win_rate  alpha_vs_xph_ann_pct
        BuyHold_Equal               9.625921    0.377820     0.613220        -17.925456  0.508982              7.737318
  EqualWeight_Monthly               8.460957    0.339634     0.554942        -18.982354  0.500998              7.237284
PPO_Phase5_RichFDA_CT               8.242213    0.335393     0.534971        -15.604897  0.483034              7.351615
                  XPH              -8.074730   -0.090723    -0.145941        -22.619079  0.491018              0.000000
         Momentum_20D              -8.401114   -0.171261    -0.254539        -24.221550  0.465070             -0.998788

CompletedProcess(args=['/Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project /.venv/bin/python', 'phase5_fda_ppo.py', '--project-root', '/Users/aj5/Main drive/UT Austin MSIS/Deep Learning/Project ', '--ablation', 'rich_fda_ct', '--timesteps', '60000', '--search-timesteps', '15000', '--seeds', '7,42', '--val-split-date', '2021-01-01', '--sent-clip', '3.0', '--seed', '42', '--window-size', '20', '--device', 'auto'], returncode=0)

In [6]:
# Inspect key outputs for all ablations
from pathlib import Path
import pandas as pd

base = Path('results')
paths = {
    'basic_metrics': base / 'phase5_basic_fda' / 'phase5_fda_metrics.csv',
    'rich_metrics': base / 'phase5_rich_fda' / 'phase5_fda_metrics.csv',
    'rich_ct_metrics': base / 'phase5_rich_fda_ct' / 'phase5_fda_metrics.csv',
    'basic_trials': base / 'phase5_basic_fda' / 'phase5_robust_search_trials.csv',
    'rich_trials': base / 'phase5_rich_fda' / 'phase5_robust_search_trials.csv',
    'rich_ct_trials': base / 'phase5_rich_fda_ct' / 'phase5_robust_search_trials.csv',
    'basic_comp': base / 'phase5_basic_fda' / 'phase3_phase4_phase5_comparison.csv',
    'rich_comp': base / 'phase5_rich_fda' / 'phase3_phase4_phase5_comparison.csv',
    'rich_ct_comp': base / 'phase5_rich_fda_ct' / 'phase3_phase4_phase5_comparison.csv',
    'basic_interp': base / 'phase5_basic_fda' / 'phase5_fda_interpretability.csv',
    'rich_interp': base / 'phase5_rich_fda' / 'phase5_fda_interpretability.csv',
    'rich_ct_interp': base / 'phase5_rich_fda_ct' / 'phase5_fda_interpretability.csv',
}

for name, p in paths.items():
    print(f'{name}:', 'OK' if p.exists() else 'MISSING', '-', p)

if paths['basic_metrics'].exists():
    print('\nBasic FDA metrics:')
    display(pd.read_csv(paths['basic_metrics']))
if paths['rich_metrics'].exists():
    print('\nRich FDA metrics:')
    display(pd.read_csv(paths['rich_metrics']))
if paths['rich_ct_metrics'].exists():
    print('\nRich FDA + CT metrics:')
    display(pd.read_csv(paths['rich_ct_metrics']))

basic_metrics: OK - results/phase5_basic_fda/phase5_fda_metrics.csv
rich_metrics: OK - results/phase5_rich_fda/phase5_fda_metrics.csv
rich_ct_metrics: OK - results/phase5_rich_fda_ct/phase5_fda_metrics.csv
basic_trials: OK - results/phase5_basic_fda/phase5_robust_search_trials.csv
rich_trials: OK - results/phase5_rich_fda/phase5_robust_search_trials.csv
rich_ct_trials: OK - results/phase5_rich_fda_ct/phase5_robust_search_trials.csv
basic_comp: OK - results/phase5_basic_fda/phase3_phase4_phase5_comparison.csv
rich_comp: OK - results/phase5_rich_fda/phase3_phase4_phase5_comparison.csv
rich_ct_comp: OK - results/phase5_rich_fda_ct/phase3_phase4_phase5_comparison.csv
basic_interp: OK - results/phase5_basic_fda/phase5_fda_interpretability.csv
rich_interp: OK - results/phase5_rich_fda/phase5_fda_interpretability.csv
rich_ct_interp: OK - results/phase5_rich_fda_ct/phase5_fda_interpretability.csv

Basic FDA metrics:

,strategy,cumulative_return_pct,ann_sharpe,ann_sortino,max_drawdown_pct,win_rate,alpha_vs_xph_ann_pct
0,PPO_Phase5_BasicFDA,25.431256,0.613396,1.061182,-17.527683,0.497006,16.125121
1,BuyHold_Equal,9.625921,0.377820,0.613220,-17.925456,0.508982,7.737318
2,EqualWeight_Monthly,8.460957,0.339634,0.554942,-18.982354,0.500998,7.237284
3,XPH,-8.074730,-0.090723,-0.145941,-22.619079,0.491018,0.000000
4,Momentum_20D,-8.401114,-0.171261,-0.254539,-24.221550,0.465070,-0.998788

Rich FDA metrics:

,strategy,cumulative_return_pct,ann_sharpe,ann_sortino,max_drawdown_pct,win_rate,alpha_vs_xph_ann_pct
0,BuyHold_Equal,9.625921,0.377820,0.613220,-17.925456,0.508982,7.737318
1,EqualWeight_Monthly,8.460957,0.339634,0.554942,-18.982354,0.500998,7.237284
2,PPO_Phase5_RichFDA,5.016599,0.222449,0.390616,-25.551392,0.502994,6.488123
3,XPH,-8.074730,-0.090723,-0.145941,-22.619079,0.491018,0.000000
4,Momentum_20D,-8.401114,-0.171261,-0.254539,-24.221550,0.465070,-0.998788

Rich FDA + CT metrics:

,strategy,cumulative_return_pct,ann_sharpe,ann_sortino,max_drawdown_pct,win_rate,alpha_vs_xph_ann_pct
0,BuyHold_Equal,9.625921,0.377820,0.613220,-17.925456,0.508982,7.737318
1,EqualWeight_Monthly,8.460957,0.339634,0.554942,-18.982354,0.500998,7.237284
2,PPO_Phase5_RichFDA_CT,8.242213,0.335393,0.534971,-15.604897,0.483034,7.351615
3,XPH,-8.074730,-0.090723,-0.145941,-22.619079,0.491018,0.000000
4,Momentum_20D,-8.401114,-0.171261,-0.254539,-24.221550,0.465070,-0.998788